#include "kernel/transform.cxx"
#include "utils/colourmap.cxx"
#include "cxxsupport/error_handling.cc"
#include "cxxsupport/mpi_support.cc"
#include "cxxsupport/cxxutils.cc"
#include "reader/gadget_reader.cc"
#include "writer/write_tga.cc"
#include "splotch/splotch.cc"
